CREATE TABLE destinations (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    place TEXT NOT NULL,
    description TEXT NOT NULL,
    author TEXT,
    date_added TIMESTAMPTZ DEFAULT now() NOT NULL
);